### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by Fitblip**
Hi there, thanks for the neat project. I needed to run it in a docker container, so I figured I'd share my dockerfile back to the community.

To use it:
- Build the image with `docker build -t docker-dvr-scan .` (needs to run where the Dockerfile is, `-t` can be any arbitrary tag):
    <details>
   <summary>Click for an example build output</summary>

    ```
    $ docker build -t docker-dvr-scan .
    Sending build context to Docker daemon  324.6kB
    Step 1/6 : FROM ubuntu:latest
     ---> 4e2eef94cd6b
    Step 2/6 : ENV DEBIAN_FRONTEND=noninteractive
     ---> Using cache
     ---> 744cff135320
    Step 3/6 : RUN apt-get update && apt-get install -y python3 python3-pip libgl1-mesa-glx libglib2.0-0
     ---> Running in 9f2fbd003f9f
    Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
    Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
    Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]
    ...SNIP...
    Removing intermediate container 9f2fbd003f9f
     ---> 72905e6c8d03
    Step 4/6 : RUN pip3 install dvr-scan[opencv,progress_bar]
     ---> Running in 1d50e8948e5c
    Collecting dvr-scan[opencv,progress_bar]
      Downloading dvr_scan-1.1.0-py2.py3-none-any.whl (25 kB)
    Collecting numpy
      Downloading numpy-1.19.1-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
    Collecting opencv-python; extra == "opencv"
      Downloading opencv_python-4.4.0.42-cp38-cp38-manylinux2014_x86_64.whl (49.4 MB)
    Collecting tqdm; extra == "progress_bar"
      Downloading tqdm-4.48.2-py2.py3-none-any.whl (68 kB)
    Installing collected packages: numpy, opencv-python, tqdm, dvr-scan
    Successfully installed dvr-scan-1.1.0 numpy-1.19.1 opencv-python-4.4.0.42 tqdm-4.48.2
    Removing intermediate container 1d50e8948e5c
     ---> d1b8bb06c785
    Step 5/6 : WORKDIR /video/
     ---> Running in 5bc4d9780afe
    Removing intermediate container 5bc4d9780afe
     ---> 2d5ea6d919b0
    Step 6/6 : ENTRYPOINT ["dvr-scan"]
     ---> Running in 8e64f6996adf
    Removing intermediate container 8e64f6996adf
     ---> 149e33f4090b
    Successfully built 149e33f4090b
    Successfully tagged docker-dvr-scan:latest
    ```
</details>

- Then run the docker run command like this (note, running with `-it` is vital for seeing output with the way the progress bar works):
    ```
    $ docker run --rm -it -v $(pwd):/video/ docker-dvr-scan -i ./some-video.mkv
    ```

That's about the extent of it, with the `ENTRYPOINT` configured as so anything after `docker-dvr-scan` will be passed as parameters directly to `dvr-scan`, and you can in theory have a bash alias like `alias dvr-scan="docker run --rm -it -v $(pwd):/video/ docker-dvr-scan"` and things will "just work". 

I'm not sure how familiar/comfortable you are with docker, but if you also [publish this to docker hub](https://docs.docker.com/docker-hub/publish/publish/) anyone should be able to run `docker run --rm -it -v $(pwd):/video/ Breakthrough/DVR-Scan -i some_video.mkv` without configuring anything locally. Totally understand if you don't want to sign up for yet another account though, and this Dockerfile should suffice for most folks. 

I'm also happy to update the docs with this PR, but I didn't want to take a stab without knowing how much info (basically the above) you wanted in it or where. If you give me some clues I can give it a go :D

### CODE REVIEW

**Comment by Breakthrough** [comment]
Hey @Fitblip;


I'm not hugely familiar with docker to be honest with you, but I would be okay with accepting this PR and updating the documentation.

As for the docs, how do you feel about adding it as an entry in [the FAQ](https://github.com/Breakthrough/DVR-Scan/blob/master/docs/faq.md)?  Feel free to take a crack at it - I don't think a full command output is necessary, but maybe what to expect, etc would be good.

Thanks for the PR!

**Review by Breakthrough — COMMENTED** [review]
Not familiar with Dockerfile, but should the end of this file have a newline?

**Comment by Fitblip** [comment]
Awesome, I think this should be good to go @Breakthrough! Let me know what you think and if you'd like to see any changes.

**Review by Breakthrough — APPROVED** [review]
Awesome, thanks so much @Fitblip!  Much appreciated.

**Pull request merged**
